# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/debian9"

  config.vm.hostname = 'mediaWiki-node-manager'

  config.vm.network "private_network", ip: "192.168.122.10"

  config.vm.provider "virtualbox" do |vb|
 
     vb.memory = "1024"
     vb.name = "mediaWiki-node-manager"
  end

end
